pan_and_tilt:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    pitch_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: pitch_joint
      pid: {p: 10.0, i: 0.1, d: 1.0}
    yaw_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: yaw_joint
      pid: {p: 10.0, i: 0.1, d: 1.0}
