<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="body">
    <xacro:macro name="skyscraper">     
   
    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${base_mass}" />
            <cylinder_inertia 
                m="${base_mass}" 
                r="${BASE_RADIUS}" 
                h="${BASE_RADIUS/2}"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
			<!-- <uri>model://skyscraper/meshes/skyscraper.dae</uri> -->
			<geometry>
		      <box>
		        <size>0.05 0.05 0.05</size>
		      </box>
			</geometry>
        </visual>
    </link>
    
    <link name="world"/>
    <joint name="world_base_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    </joint>

    </xacro:macro>
    
</robot>
